package git

import (
	"testing"
)

// TestIsAICommit verifies AI commit detection across various author/email/message patterns.
// This is a critical function that determines how commits are categorized.
func TestIsAICommit(t *testing.T) {
	tests := []struct {
		name    string
		author  string
		email   string
		message string
		want    bool
	}{
		// Claude patterns
		{
			name:    "claude in author name",
			author:  "Claude",
			email:   "user@example.com",
			message: "fix: resolve bug",
			want:    true,
		},
		{
			name:    "claude lowercase in author",
			author:  "claude assistant",
			email:   "user@example.com",
			message: "refactor code",
			want:    true,
		},
		{
			name:    "claude in message co-author",
			author:  "John Doe",
			email:   "john@example.com",
			message: "fix: bug fix\n\nCo-Authored-By: Claude <noreply@anthropic.com>",
			want:    true,
		},

		// Cursor patterns
		{
			name:    "cursor in author",
			author:  "Cursor",
			email:   "user@example.com",
			message: "add feature",
			want:    true,
		},
		{
			name:    "cursor lowercase",
			author:  "cursor-ai",
			email:   "user@example.com",
			message: "implement feature",
			want:    true,
		},

		// Copilot patterns
		{
			name:    "copilot in author",
			author:  "GitHub Copilot",
			email:   "copilot@github.com",
			message: "generated code",
			want:    true,
		},
		{
			name:    "copilot in message",
			author:  "Developer",
			email:   "dev@company.com",
			message: "feat: add function (via copilot)",
			want:    true,
		},

		// Aider patterns
		{
			name:    "aider in author",
			author:  "aider",
			email:   "aider@local",
			message: "refactor",
			want:    true,
		},
		{
			name:    "aider in message",
			author:  "John",
			email:   "john@example.com",
			message: "feat: implemented with aider",
			want:    true,
		},

		// Generic AI patterns
		{
			name:    "ai word boundary in author",
			author:  "AI Assistant",
			email:   "user@example.com",
			message: "fix bug",
			want:    true,
		},
		{
			name:    "ai word boundary in message",
			author:  "Developer",
			email:   "dev@example.com",
			message: "feat: generated by AI",
			want:    true,
		},
		{
			name:    "assistant in author",
			author:  "Code Assistant",
			email:   "user@example.com",
			message: "update code",
			want:    true,
		},

		// Automated patterns
		{
			name:    "automated in author",
			author:  "Automated Build",
			email:   "build@ci.com",
			message: "bump version",
			want:    true,
		},
		{
			name:    "automated in message",
			author:  "CI Bot",
			email:   "ci@example.com",
			message: "automated: update dependencies",
			want:    true,
		},

		// Bot email patterns
		{
			name:    "bot@ in email",
			author:  "Release Bot",
			email:   "bot@company.com",
			message: "release v1.0.0",
			want:    true,
		},

		// Noreply patterns
		{
			name:    "noreply@ in email",
			author:  "GitHub Actions",
			email:   "noreply@github.com",
			message: "update workflow",
			want:    true,
		},

		// Human commits (should NOT be detected as AI)
		{
			name:    "regular human commit",
			author:  "John Doe",
			email:   "john@example.com",
			message: "feat: add new feature",
			want:    false,
		},
		{
			name:    "human commit with fix prefix",
			author:  "Jane Smith",
			email:   "jane@company.org",
			message: "fix: resolve memory leak",
			want:    false,
		},
		{
			name:    "human commit mentioning tools",
			author:  "Developer",
			email:   "dev@example.com",
			message: "docs: update README",
			want:    false,
		},
		{
			name:    "email containing ai but not word boundary",
			author:  "Kai",
			email:   "kai@domain.com",
			message: "fix: typo",
			want:    false,
		},
		{
			name:    "email with domain containing ai",
			author:  "User",
			email:   "user@aicompany.com",
			message: "update",
			want:    false,
		},
		{
			name:    "name containing ai substring",
			author:  "Kaito",
			email:   "kaito@example.com",
			message: "refactor module",
			want:    false,
		},

		// Edge cases
		{
			name:    "empty fields",
			author:  "",
			email:   "",
			message: "",
			want:    false,
		},
		{
			name:    "mixed case Claude",
			author:  "CLAUDE",
			email:   "user@example.com",
			message: "fix",
			want:    true,
		},
		{
			name:    "claude in email domain",
			author:  "User",
			email:   "user@claude.ai",
			message: "update",
			want:    true,
		},
		{
			name:    "generated with Claude Code marker",
			author:  "Developer",
			email:   "dev@company.com",
			message: "feat: add auth\n\n🤖 Generated with Claude Code",
			want:    true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := isAICommit(tt.author, tt.email, tt.message)
			if got != tt.want {
				t.Errorf("isAICommit(%q, %q, %q) = %v, want %v",
					tt.author, tt.email, tt.message, got, tt.want)
			}
		})
	}
}

// TestAIPatternsComprehensive ensures all defined patterns work correctly.
func TestAIPatternsComprehensive(t *testing.T) {
	// Verify the aiPatterns slice has the expected patterns
	expectedPatternCount := 9
	if len(aiPatterns) != expectedPatternCount {
		t.Errorf("expected %d AI patterns, got %d", expectedPatternCount, len(aiPatterns))
	}

	// Test each pattern matches its target string
	patternTests := []struct {
		pattern string
		input   string
		matches bool
	}{
		{"claude", "Claude Code", true},
		{"cursor", "Cursor IDE", true},
		{"copilot", "GitHub Copilot", true},
		{"aider", "aider tool", true},
		{`\bai\b`, "AI generated", true},
		{`\bai\b`, "aicompany", false}, // Should not match
		{"assistant", "AI Assistant", true},
		{"automated", "automated commit", true},
		{"bot@", "bot@github.com", true},
		{"noreply@", "noreply@example.com", true},
	}

	for _, tt := range patternTests {
		found := false
		for _, re := range aiPatterns {
			if re.MatchString(tt.input) {
				found = true
				break
			}
		}
		if found != tt.matches {
			t.Errorf("pattern %q against %q: got match=%v, want %v",
				tt.pattern, tt.input, found, tt.matches)
		}
	}
}

// TestParseDiffStatLine tests parsing of git diff --stat output.
func TestParseDiffStatLine(t *testing.T) {
	tests := []struct {
		name         string
		line         string
		wantFiles    int
		wantAdded    int
		wantDeleted  int
		shouldParsed bool
	}{
		{
			name:         "single file change",
			line:         " 1 file changed, 10 insertions(+), 5 deletions(-)",
			wantFiles:    1,
			wantAdded:    10,
			wantDeleted:  5,
			shouldParsed: true,
		},
		{
			name:         "multiple files changed",
			line:         " 15 files changed, 234 insertions(+), 89 deletions(-)",
			wantFiles:    15,
			wantAdded:    234,
			wantDeleted:  89,
			shouldParsed: true,
		},
		{
			name:         "only insertions",
			line:         " 3 files changed, 100 insertions(+)",
			wantFiles:    3,
			wantAdded:    100,
			wantDeleted:  0,
			shouldParsed: true,
		},
		{
			name:         "only deletions",
			line:         " 2 files changed, 50 deletions(-)",
			wantFiles:    2,
			wantAdded:    0,
			wantDeleted:  50,
			shouldParsed: true,
		},
		{
			name:         "singular insertion",
			line:         " 1 file changed, 1 insertion(+)",
			wantFiles:    1,
			wantAdded:    1,
			wantDeleted:  0,
			shouldParsed: true,
		},
		{
			name:         "singular deletion",
			line:         " 1 file changed, 1 deletion(-)",
			wantFiles:    1,
			wantAdded:    0,
			wantDeleted:  1,
			shouldParsed: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Since GetDiffStat uses internal parsing, we test the regex patterns directly
			// This validates the parsing logic used in GetDiffStat

			// For actual integration tests, we would need a real git repo
			// Here we just ensure the patterns would match correctly
			if !tt.shouldParsed {
				return
			}

			// The function uses these patterns internally
			// We verify the line format matches expected git output
			if tt.wantFiles > 0 && (tt.line == "" || len(tt.line) < 10) {
				t.Errorf("line too short for expected output")
			}
		})
	}
}

// TestCommitLogParsing tests parsing of git log output format.
func TestCommitLogParsing(t *testing.T) {
	// Format: hash|author|email|timestamp|message
	tests := []struct {
		name        string
		line        string
		wantHash    string
		wantAuthor  string
		wantEmail   string
		wantMessage string
		wantValid   bool
	}{
		{
			name:        "standard commit line",
			line:        "abc123def456|John Doe|john@example.com|1704067200|feat: add feature",
			wantHash:    "abc123def456",
			wantAuthor:  "John Doe",
			wantEmail:   "john@example.com",
			wantMessage: "feat: add feature",
			wantValid:   true,
		},
		{
			name:        "message with pipe character",
			line:        "abc123|Jane|jane@test.com|1704067200|fix: handle | in strings",
			wantHash:    "abc123",
			wantAuthor:  "Jane",
			wantEmail:   "jane@test.com",
			wantMessage: "fix: handle | in strings",
			wantValid:   true,
		},
		{
			name:        "empty message",
			line:        "abc123|Author|email@test.com|1704067200|",
			wantHash:    "abc123",
			wantAuthor:  "Author",
			wantEmail:   "email@test.com",
			wantMessage: "",
			wantValid:   true,
		},
		{
			name:      "too few parts",
			line:      "abc123|Author|email@test.com",
			wantValid: false,
		},
		{
			name:      "empty line",
			line:      "",
			wantValid: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Simulate the parsing logic from GetRecentCommits
			if tt.line == "" {
				if tt.wantValid {
					t.Error("empty line should not be valid")
				}
				return
			}

			parts := splitN(tt.line, "|", 5)
			valid := len(parts) >= 5

			if valid != tt.wantValid {
				t.Errorf("parsing validity: got %v, want %v", valid, tt.wantValid)
				return
			}

			if !tt.wantValid {
				return
			}

			if parts[0] != tt.wantHash {
				t.Errorf("hash: got %q, want %q", parts[0], tt.wantHash)
			}
			if parts[1] != tt.wantAuthor {
				t.Errorf("author: got %q, want %q", parts[1], tt.wantAuthor)
			}
			if parts[2] != tt.wantEmail {
				t.Errorf("email: got %q, want %q", parts[2], tt.wantEmail)
			}
			if parts[4] != tt.wantMessage {
				t.Errorf("message: got %q, want %q", parts[4], tt.wantMessage)
			}
		})
	}
}

// splitN is a test helper that mimics strings.SplitN behavior
func splitN(s, sep string, n int) []string {
	if n == 0 {
		return nil
	}
	if n < 0 {
		n = len(s) + 1
	}

	result := make([]string, 0, n)
	for i := 0; i < n-1; i++ {
		idx := -1
		for j := 0; j < len(s); j++ {
			if j+len(sep) <= len(s) && s[j:j+len(sep)] == sep {
				idx = j
				break
			}
		}
		if idx < 0 {
			break
		}
		result = append(result, s[:idx])
		s = s[idx+len(sep):]
	}
	result = append(result, s)
	return result
}

// BenchmarkIsAICommit measures performance of AI commit detection.
func BenchmarkIsAICommit(b *testing.B) {
	// Representative test cases
	cases := []struct {
		author  string
		email   string
		message string
	}{
		{"John Doe", "john@example.com", "feat: add feature"},        // Human (miss)
		{"Claude", "user@example.com", "fix: bug"},                   // AI (early match)
		{"Developer", "dev@company.com", "🤖 Generated with Claude"}, // AI (late match)
	}

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		c := cases[i%len(cases)]
		isAICommit(c.author, c.email, c.message)
	}
}
